In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/logistics_shipments_dataset.csv')
df.head()

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
0,SH10000,Warehouse_MIA,San Francisco,UPS,2023-10-02,2023-10-04,25.7,67.46,Delivered,291,2
1,SH10001,Warehouse_MIA,Atlanta,DHL,2023-12-06,2023-12-09,38.9,268.85,Delivered,1225,3
2,SH10002,Warehouse_LA,Houston,DHL,2023-09-18,2023-09-20,37.2,74.35,Delivered,220,2
3,SH10003,Warehouse_BOS,Seattle,OnTrac,2023-01-26,2023-02-04,42.6,187.04,Delivered,1156,9
4,SH10004,Warehouse_SF,Dallas,OnTrac,2023-06-03,2023-06-06,7.9,120.01,Delivered,1017,3

In [3]:
df.shape

(2000, 11)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment_ID       2000 non-null   object
 1   Origin_Warehouse  2000 non-null   object
 2   Destination       2000 non-null   object
 3   Carrier           2000 non-null   object
 4   Shipment_Date     2000 non-null   object
 5   Delivery_Date     1968 non-null   object
 6   Weight_kg         2000 non-null   float64
 7   Cost              1959 non-null   float64
 8   Status            2000 non-null   object
 9   Distance_miles    2000 non-null   int64
 10  Transit_Days      2000 non-null   int64
dtypes: float64(2), int64(2), object(7)
memory usage: 172.0+ KB

In [5]:
df.describe()

         Weight_kg         Cost  Distance_miles  Transit_Days
count  2000.000000  1959.000000     2000.000000   2000.000000
mean     30.184800   205.161598     1275.868000      4.182500
std     124.967053   222.586082      691.382829      1.837902
min       0.000000    17.890000      101.000000      1.000000
25%      12.300000   117.710000      690.250000      3.000000
50%      20.700000   196.420000     1262.500000      4.000000
75%      33.925000   272.115000     1867.250000      5.000000
max    5404.200000  6562.210000     2499.000000     12.000000

In [6]:
df.sample(10)

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
1676,SH11676,Warehouse_ATL,Detroit,Amazon Logistics,2023-08-05,2023-08-12,11.4,263.34,Delivered,2178,7
1081,SH11081,Warehouse_CHI,Miami,Amazon Logistics,2023-07-23,2023-07-26,84.6,260.78,In Transit,1350,3
676,SH10676,Warehouse_MIA,Los Angeles,DHL,2023-10-27,2023-11-01,43.7,401.12,Delivered,2460,5
1913,SH11913,Warehouse_NYC,Miami,LaserShip,2023-02-06,2023-02-10,49.0,265.52,Delivered,1875,4
290,SH10290,Warehouse_LA,Dallas,OnTrac,2023-11-09,2023-11-13,10.6,235.34,Delivered,1435,4
1994,SH11994,Warehouse_SF,Seattle,Amazon Logistics,2023-11-10,2023-11-12,59.7,130.00,Delivered,237,2
1756,SH11756,Warehouse_LA,Phoenix,OnTrac,2023-07-16,2023-07-17,94.0,143.20,Delivered,373,1
136,SH10136,Warehouse_CHI,Miami,FedEx,2023-11-04,2023-11-10,15.9,257.13,Delivered,1350,6
947,SH10947,Warehouse_ATL,Atlanta,UPS,2023-10-17,2023-10-23,53.8,334.19,Delivered,2107,6
1736,SH11736,Warehouse_SF,Phoenix,LaserShip,2023-10-24,2023-11-01,32.0,301.33,Delivered,2356,8

In [7]:
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'])
df['Shipment_Date']=pd.to_datetime(df['Shipment_Date'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment_ID       2000 non-null   object
 1   Origin_Warehouse  2000 non-null   object
 2   Destination       2000 non-null   object
 3   Carrier           2000 non-null   object
 4   Shipment_Date     2000 non-null   datetime64[ns]
 5   Delivery_Date     1968 non-null   datetime64[ns]
 6   Weight_kg         2000 non-null   float64
 7   Cost              1959 non-null   float64
 8   Status            2000 non-null   object
 9   Distance_miles    2000 non-null   int64
 10  Transit_Days      2000 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(2), object(5)
memory usage: 172.0+ KB

In [9]:
df.sample(10)

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days
213,SH10213,Warehouse_ATL,Denver,Amazon Logistics,2023-08-28,2023-09-05,28.5,284.40,Delivered,2074,8
905,SH10905,Warehouse_HOU,Miami,OnTrac,2023-10-23,2023-10-26,59.4,192.19,Delivered,1118,3
699,SH10699,Warehouse_HOU,Dallas,UPS,2023-02-28,2023-03-05,78.2,195.05,Delayed,860,3
1852,SH11852,Warehouse_SF,Atlanta,Amazon Logistics,2023-02-23,2023-03-02,6.6,81.82,Delayed,613,5
1181,SH11181,Warehouse_SF,Miami,OnTrac,2023-07-18,2023-07-21,7.2,139.61,Delivered,1122,3
621,SH10621,Warehouse_BOS,Portland,USPS,2023-11-14,2023-11-22,21.4,276.47,Delivered,1837,8
294,SH10294,Warehouse_DEN,Atlanta,UPS,2023-05-30,2023-06-04,4.1,237.12,Delivered,1790,5
261,SH10261,Warehouse_HOU,Detroit,DHL,2023-12-24,2023-12-28,39.2,159.90,Delivered,605,4
1125,SH11125,Warehouse_DEN,New York,DHL,2023-12-25,2023-12-29,14.3,256.96,Delivered,1446,4
287,SH10287,Warehouse_DEN,Minneapolis,DHL,2023-09-19,2023-09-23,75.9,251.01,Delivered,939,4

### Loading the US diesel price dataset

In [10]:
df_fuel=pd.read_csv("/content/us diesel price.csv")

In [11]:
df_fuel.sample(10)

,Date,Weekly U.S. No 2 Diesel Retail Prices (Dollars per Gallon),Weekly East Coast No 2 Diesel Retail Prices (Dollars per Gallon),Weekly New England (PADD 1A) No 2 Diesel Retail Prices (Dollars per Gallon),Weekly Central Atlantic (PADD 1B) No 2 Diesel Retail Prices (Dollars per Gallon),Weekly Lower Atlantic (PADD 1C) No 2 Diesel Retail Prices (Dollars per Gallon),Weekly Midwest No 2 Diesel Retail Prices (Dollars per Gallon),Weekly Gulf Coast No 2 Diesel Retail Prices (Dollars per Gallon),Weekly Rocky Mountain No 2 Diesel Retail Prices (Dollars per Gallon),Weekly West Coast No 2 Diesel Retail Prices (Dollars per Gallon),Weekly California No 2 Diesel Retail Prices (Dollars per Gallon),Weekly West Coast (PADD 5) Except California No 2 Diesel Retail Prices (Dollars per Gallon)
736,"Apr 28, 2008",4.177,4.230,4.346,4.376,4.157,4.133,4.113,4.141,4.312,4.390,NaN
206,"Mar 02, 1998",1.074,1.089,1.163,1.164,1.050,1.062,1.048,1.095,1.114,1.186,NaN
885,"Mar 07, 2011",3.871,3.908,4.046,4.014,3.850,3.823,3.812,3.845,4.046,4.122,NaN
1070,"Sep 22, 2014",3.778,3.804,3.886,3.886,3.722,3.713,3.696,3.841,3.990,4.041,3.929
52,"Mar 20, 1995",1.085,1.088,NaN,NaN,NaN,1.065,1.043,1.106,1.201,NaN,NaN
1520,"May 08, 2023",3.922,3.986,4.374,4.289,3.834,3.827,3.613,4.105,4.630,4.847,4.438
248,"Dec 21, 1998",0.968,0.976,1.077,1.065,0.929,0.946,0.939,0.993,1.062,1.118,NaN
1177,"Oct 10, 2016",2.445,2.441,2.453,2.540,2.363,2.417,2.317,2.508,2.712,2.809,2.591
913,"Sep 19, 2011",3.833,3.853,3.983,3.968,3.792,3.799,3.765,3.892,3.977,4.062,NaN
1282,"Oct 15, 2018",3.394,3.382,3.361,3.544,3.272,3.351,3.172,3.400,3.880,4.109,3.591

In [12]:
df_fuel.columns

Index(['Date', 'Weekly U.S. No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly East Coast No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly New England (PADD 1A) No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly Central Atlantic (PADD 1B) No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly Lower Atlantic (PADD 1C) No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly Midwest No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly Gulf Coast No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly Rocky Mountain No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly West Coast No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly California No 2 Diesel Retail Prices  (Dollars per Gallon)',
       'Weekly West Coast (PADD 5) Except California No 2 Diesel Retail Prices  (Dollars per Gallon)'],
      dtype='object')

In [13]:
df_fuel = df_fuel[['Date', 'Weekly U.S. No 2 Diesel Retail Prices  (Dollars per Gallon)']]

In [14]:
df_fuel.rename(columns={'Weekly U.S. No 2 Diesel Retail Prices  (Dollars per Gallon)':'Fuel_Price'},inplace=True)

In [15]:
df_fuel.head()

           Date  Fuel_Price
0  Mar 21, 1994       1.106
1  Mar 28, 1994       1.107
2  Apr 04, 1994       1.109
3  Apr 11, 1994       1.108
4  Apr 18, 1994       1.105

In [16]:
df_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1671 non-null   object
 1   Fuel_Price  1671 non-null   float64
dtypes: float64(1), object(1)
memory usage: 26.2+ KB

In [17]:
df_fuel['Date']=pd.to_datetime(df_fuel['Date'])

In [18]:
df_fuel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        1671 non-null   datetime64[ns]
 1   Fuel_Price  1671 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 26.2 KB

In [19]:
df_fuel.head()

        Date  Fuel_Price
0 1994-03-21       1.106
1 1994-03-28       1.107
2 1994-04-04       1.109
3 1994-04-11       1.108
4 1994-04-18       1.105

In [20]:
df['Shipment_Date'].dt.year.unique()

array([2023], dtype=int32)

In [21]:
df_fuel=df_fuel[df_fuel['Date'].dt.year==2023]

In [22]:
df_fuel.shape

(52, 2)

In [23]:
df_fuel['Date']

1502   2023-01-02
1503   2023-01-09
1504   2023-01-16
1505   2023-01-23
1506   2023-01-30
1507   2023-02-06
1508   2023-02-13
1509   2023-02-20
1510   2023-02-27
1511   2023-03-06
1512   2023-03-13
1513   2023-03-20
1514   2023-03-27
1515   2023-04-03
1516   2023-04-10
1517   2023-04-17
1518   2023-04-24
1519   2023-05-01
1520   2023-05-08
1521   2023-05-15
1522   2023-05-22
1523   2023-05-29
1524   2023-06-05
1525   2023-06-12
1526   2023-06-19
1527   2023-06-26
1528   2023-07-03
1529   2023-07-10
1530   2023-07-17
1531   2023-07-24
1532   2023-07-31
1533   2023-08-07
1534   2023-08-14
1535   2023-08-21
1536   2023-08-28
1537   2023-09-04
1538   2023-09-11
1539   2023-09-18
1540   2023-09-25
1541   2023-10-02
1542   2023-10-09
1543   2023-10-16
1544   2023-10-23
1545   2023-10-30
1546   2023-11-06
1547   2023-11-13
1548   2023-11-20
1549   2023-11-27
1550   2023-12-04
1551   2023-12-11
1552   2023-12-18
1553   2023-12-25
Name: Date, dtype: datetime64[ns]

In [24]:
df_fuel[df_fuel['Date'].dt.month==1]

           Date  Fuel_Price
1502 2023-01-02       4.583
1503 2023-01-09       4.549
1504 2023-01-16       4.524
1505 2023-01-23       4.604
1506 2023-01-30       4.622

In [25]:
temp=df[(df['Shipment_Date'].dt.month==1)]

In [26]:
temp['Shipment_Date'].unique()

<DatetimeArray>
['2023-01-26 00:00:00', '2023-01-19 00:00:00', '2023-01-25 00:00:00',
 '2023-01-16 00:00:00', '2023-01-17 00:00:00', '2023-01-07 00:00:00',
 '2023-01-27 00:00:00', '2023-01-14 00:00:00', '2023-01-05 00:00:00',
 '2023-01-03 00:00:00', '2023-01-06 00:00:00', '2023-01-21 00:00:00',
 '2023-01-01 00:00:00', '2023-01-31 00:00:00', '2023-01-15 00:00:00',
 '2023-01-11 00:00:00', '2023-01-18 00:00:00', '2023-01-04 00:00:00',
 '2023-01-30 00:00:00', '2023-01-10 00:00:00', '2023-01-12 00:00:00',
 '2023-01-20 00:00:00', '2023-01-22 00:00:00', '2023-01-08 00:00:00',
 '2023-01-02 00:00:00', '2023-01-28 00:00:00', '2023-01-13 00:00:00',
 '2023-01-29 00:00:00', '2023-01-23 00:00:00', '2023-01-24 00:00:00',
 '2023-01-09 00:00:00']
Length: 31, dtype: datetime64[ns]

In [27]:
df = df.sort_values('Shipment_Date')
df_fuel = df_fuel.sort_values('Date')

In [28]:
final_df = pd.merge_asof(
    df,
    df_fuel,
    left_on='Shipment_Date',
    right_on='Date',
    direction='backward'
)

In [29]:
final_df.sample(10)

,Shipment_ID,Origin_Warehouse,Destination,Carrier,Shipment_Date,Delivery_Date,Weight_kg,Cost,Status,Distance_miles,Transit_Days,Date,Fuel_Price
1918,SH11951,Warehouse_CHI,Los Angeles,DHL,2023-12-19,2023-12-21,10.1,42.45,Delivered,169,2,2023-12-18,3.894
1144,SH11105,Warehouse_LA,San Francisco,LaserShip,2023-08-03,2023-08-10,54.6,6562.21,Delivered,1942,7,2023-07-31,4.127
798,SH10069,Warehouse_SEA,Houston,FedEx,2023-05-31,2023-06-04,35.7,180.20,Delivered,989,4,2023-05-29,3.855
71,SH11844,Warehouse_NYC,Dallas,Amazon Logistics,2023-01-15,2023-01-21,27.4,NaN,Delivered,1518,6,2023-01-09,4.549
1334,SH10496,Warehouse_MIA,Denver,FedEx,2023-09-03,2023-09-06,68.5,235.28,Delivered,1058,3,2023-08-28,4.475
126,SH10747,Warehouse_ATL,Los Angeles,USPS,2023-01-25,2023-01-27,16.8,124.30,Delivered,1003,2,2023-01-23,4.604
506,SH11851,Warehouse_NYC,Portland,USPS,2023-04-07,2023-04-13,20.8,289.20,Delivered,2420,6,2023-04-03,4.105
233,SH10053,Warehouse_BOS,Dallas,UPS,2023-02-18,2023-02-23,26.6,277.97,Delivered,1847,5,2023-02-13,4.444
95,SH10418,Warehouse_ATL,Chicago,DHL,2023-01-18,2023-01-25,10.0,360.44,Delivered,2344,7,2023-01-16,4.524
285,SH10462,Warehouse_SEA,Minneapolis,USPS,2023-02-27,2023-03-05,31.3,308.28,Delivered,2454,6,2023-02-27,4.294

In [30]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Shipment_ID       2000 non-null   object
 1   Origin_Warehouse  2000 non-null   object
 2   Destination       2000 non-null   object
 3   Carrier           2000 non-null   object
 4   Shipment_Date     2000 non-null   datetime64[ns]
 5   Delivery_Date     1968 non-null   datetime64[ns]
 6   Weight_kg         2000 non-null   float64
 7   Cost              1959 non-null   float64
 8   Status            2000 non-null   object
 9   Distance_miles    2000 non-null   int64
 10  Transit_Days      2000 non-null   int64
 11  Date              1996 non-null   datetime64[ns]
 12  Fuel_Price        1996 non-null   float64
dtypes: datetime64[ns](3), float64(3), int64(2), object(5)
memory usage: 203.3+ KB

In [31]:
final_df['Shipment_Month'] = final_df['Shipment_Date'].dt.month
final_df['Shipment_DayOfWeek'] = final_df['Shipment_Date'].dt.dayofweek

In [32]:
cols_to_drop = [
    'Shipment_ID',
    'Shipment_Date',
    'Delivery_Date',
    'Status',
    'Transit_Days',
    'Date'
]
final_df = final_df.drop(columns=cols_to_drop)

In [33]:
final_df.sample(10)

,Origin_Warehouse,Destination,Carrier,Weight_kg,Cost,Distance_miles,Fuel_Price,Shipment_Month,Shipment_DayOfWeek
108,Warehouse_DEN,Phoenix,Amazon Logistics,19.4,40.24,152,4.524,1,5
1958,Warehouse_DEN,New York,DHL,14.3,256.96,1446,3.914,12,0
1913,Warehouse_LA,San Francisco,Amazon Logistics,19.0,224.00,1524,3.894,12,0
1041,Warehouse_BOS,Los Angeles,UPS,25.6,128.53,740,3.806,7,6
785,Warehouse_NYC,Chicago,USPS,19.5,122.68,790,3.883,5,6
1791,Warehouse_MIA,Dallas,UPS,17.9,336.25,2051,4.209,11,5
757,Warehouse_HOU,Boston,DHL,16.2,219.44,1509,3.883,5,1
1502,Warehouse_MIA,Denver,Amazon Logistics,18.3,119.10,860,4.593,10,2
693,Warehouse_ATL,Dallas,OnTrac,50.3,257.68,1485,3.922,5,4
226,Warehouse_HOU,Atlanta,OnTrac,21.1,109.65,800,4.444,2,5

In [34]:
final_df['Origin_Warehouse'].unique()

array(['Warehouse_CHI', 'Warehouse_SEA', 'Warehouse_BOS', 'Warehouse_ATL',
       'Warehouse_NYC', 'Warehouse_LA', 'Warehouse_MIA', 'Warehouse_SF',
       'Warehouse_DEN', 'Warehouse_HOU'], dtype=object)

In [35]:
final_df['Destination'].unique()

array(['Denver', 'Portland', 'Los Angeles', 'Minneapolis', 'Houston',
       'Dallas', 'New York', 'Miami', 'Boston', 'Seattle',
       'San Francisco', 'Chicago', 'Atlanta', 'Detroit', 'Phoenix'],
      dtype=object)

In [36]:
final_df['Carrier'].unique()

array(['USPS', 'Amazon Logistics', 'LaserShip', 'FedEx', 'DHL', 'OnTrac',
       'UPS'], dtype=object)

In [37]:
categorical_cols = ['Origin_Warehouse', 'Destination', 'Carrier']
final_ml_df = pd.get_dummies(final_df, columns=categorical_cols, drop_first=True)

In [38]:
final_ml_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Weight_kg                       2000 non-null   float64
 1   Cost                            1959 non-null   float64
 2   Distance_miles                  2000 non-null   int64
 3   Fuel_Price                      1996 non-null   float64
 4   Shipment_Month                  2000 non-null   int32
 5   Shipment_DayOfWeek              2000 non-null   int32
 6   Origin_Warehouse_Warehouse_BOS  2000 non-null   bool
 7   Origin_Warehouse_Warehouse_CHI  2000 non-null   bool
 8   Origin_Warehouse_Warehouse_DEN  2000 non-null   bool
 9   Origin_Warehouse_Warehouse_HOU  2000 non-null   bool
 10  Origin_Warehouse_Warehouse_LA   2000 non-null   bool
 11  Origin_Warehouse_Warehouse_MIA  2000 non-null   bool
 12  Origin_Warehouse_Warehouse_NYC  2000 non-null   bool
 13  Origin_Warehouse_Warehouse_SEA  2000 non-null   bool
 14  Origin_Warehouse_Warehouse_SF   2000 non-null   bool
 15  Destination_Boston              2000 non-null   bool
 16  Destination_Chicago             2000 non-null   bool
 17  Destination_Dallas              2000 non-null   bool
 18  Destination_Denver              2000 non-null   bool
 19  Destination_Detroit             2000 non-null   bool
 20  Destination_Houston             2000 non-null   bool
 21  Destination_Los Angeles         2000 non-null   bool
 22  Destination_Miami               2000 non-null   bool
 23  Destination_Minneapolis         2000 non-null   bool
 24  Destination_New York            2000 non-null   bool
 25  Destination_Phoenix             2000 non-null   bool
 26  Destination_Portland            2000 non-null   bool
 27  Destination_San Francisco       2000 non-null   bool
 28  Destination_Seattle             2000 non-null   bool
 29  Carrier_DHL                     2000 non-null   bool
 30  Carrier_FedEx                   2000 non-null   bool
 31  Carrier_LaserShip               2000 non-null   bool
 32  Carrier_OnTrac                  2000 non-null   bool
 33  Carrier_UPS                     2000 non-null   bool
 34  Carrier_USPS                    2000 non-null   bool
dtypes: bool(29), float64(3), int32(2), int64(1)
memory usage: 134.9 KB

In [39]:
final_ml_df=final_ml_df.dropna()

In [40]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error
import numpy as np

X = final_ml_df.drop(columns=['Cost'])
y = final_ml_df['Cost']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training on {X_train.shape[0]} shipments. Testing on {X_test.shape[0]} shipments.")

Training on 1564 shipments. Testing on 391 shipments.

In [41]:
xgbmodel = xgb.XGBRegressor(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgbmodel.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [42]:
predictions = xgbmodel.predict(X_test)

mae = mean_absolute_error(y_test, predictions)
mape = mean_absolute_percentage_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))

print(f"MAE (Mean Absolute Error): ${mae:.2f}")
print(f"MAPE (Percentage Error):   {mape * 100:.2f}%")
print(f"RMSE (Root Mean Squared):  ${rmse:.2f}")

MAE (Mean Absolute Error): $30.80
MAPE (Percentage Error):   11.82%
RMSE (Root Mean Squared):  $162.01